version: '2'
services:
  app:
    build: .
    image: bitfinex_algo
    working_dir: /app/src
    depends_on:
      - db
    command: sh -c "python -m unittest tests.test_bitfinex_algo.ConfigTests && python -mbitfinex_algo"
  db:
    image: mysql:5.7
    ports:
      - 3307:3306
    expose:
      - 3306
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bitfinex_algo
    volumes:
      - ./mysql-db:/docker-entrypoint-initdb.d/:ro

volumes:
  mysql-db:
